site_name: PEOPLE-ER Spectral Recovery
site_url: https://PEOPLE-ER.github.io/Spectral-Recovery/

nav:
- Home: index.md
- Documentation:
    - Getting Started:
      - Installation: 'installation.md'
      - Quick Overview: 'overview.ipynb'
    - User Guide:
      - Terminology: 'terminology.md'
      - Reading in Data: 'reading_in_data.md'
      - Computing Indices: 'indices.md'
      - Recovery Targets: 'recovery_targets.md'
      - Plotting: 'plotting.md'
      - Recovery Metrics: 'recovery_metrics.md'
      - Computing with Dask: 'computing_with_dask.md'
    - API Reference: 'api.md'
- Theoretical Basis:
  - Introduction: 'theoretical_basis.md'
  - Spectral Recovery Tool: 'spectral_recovery_tool.md'
- Tutorials:
  - For Users:
    - Getting Started:
      - Installation: 'installation.md'
      - Quick Overview: 'overview.md'
    - User Guide:
      - Terminology: 'terminology.md'
  # - For Developers:

plugins:
  - mkdocs-jupyter:
      include_source: True
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
theme: material
  features:
    - content.code.copy

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
