site_name: PEOPLE-ER Spectral Recovery
site_url: https://PEOPLE-ER.github.io/Spectral-Recovery/

nav:
- Home: index.md
- Documentation: 
    - Getting Started:
      - Quick Overview: 'overview_API.ipynb'
      - Using the CLI: 'overview_CLI.ipynb'
    - User Guide: 'about.md'
    - API Reference: 'api.md'

plugins:
  - mkdocs-jupyter:
      include_source: True
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
theme: flatly

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js