site_name: PEOPLE-ER Spectral Recovery
site_url: https://PEOPLE-ER.github.io/Spectral-Recovery/
repo_name: Spectral-Recovery
repo_url: https://github.com/PEOPLE-ER/Spectral-Recovery

nav:
- Home: index.md
- Documentation:
    - Getting Started:
      - Installation: 'installation.md'
      - Quick Overview: 'overview.md'
    - User Guide:
      - Terminology: 'terminology.md'
      - Reading in Data: 'reading_in_data.md'
      - Computing Indices: 'indices.md'
      - Recovery Targets: 'recovery_targets.md'
      - Plotting: 'plotting.md'
      - Recovery Metrics: 'recovery_metrics.md'
      - Computing with Dask: 'computing_with_dask.md'
- Theoretical Basis:
  - Introduction: 'theoretical_basis.md'
  - Spectral Recovery Tool: 'spectral_recovery_tool.md'
- API Reference: 'api.md'

# - Tutorials:
#   - For Users:
#     - Getting Started:
#       - Installation: 'installation.md'
#       - Quick Overview: 'overview.md'
#     - User Guide:
#       - Terminology: 'terminology.md'
#       - Reading in Data: 'reading_in_data.md'
#       - Recovery Targets:
#         - Historic and Reference Targets: 'historic_reference_targets.md'
#         - Historic Recovery Methods: 'historic_recovery_methods.md'
  # - For Developers:

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            # # paths: [src]
            # show_submodules: true
            docstring_options:
              ignore_init_summary: true
            # docstring_section_style: list
            # filters: ["!^_", "!_"]
  - search

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme: 
  name: material
  features: 
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css