site_name: PEOPLE-ER Spectral Recovery
site_url: https://PEOPLE-ER.github.io/Spectral-Recovery/

nav:
- Home: index.md
- Documentation: # this all needs to be updated
    - using_spectral_recovery.ipynb: 'using_spectral_recovery.ipynb'
    #- 02_landscape_segmentation.ipynb: '02_landscape_segmentation.ipynb'
    #- 03_compile_time_series.ipynb: '03_compile_time_series.ipynb'
    #- 04_cluster_analysis.ipynb: '04_cluster_analysis.ipynb'
    #- 05_calculate_dtw.ipynb: '05_calculate_dtw.ipynb'

plugins:
  - mkdocs-jupyter:
      include_source: True

markdown_extensions:
  - attr_list
theme: flatly